project:
  type: book
  output-dir: docs

engine: knitr

book:
  title: "Mutation Load in Black Grouse"
  author: "Rebecca S. Chen"
  chapters:
    - index.qmd
    - qmd/1_snpeff.qmd
    - qmd/2_gerp.qmd
    - qmd/3_load.qmd
    - qmd/4_models.qmd
    - qmd/5_per_region.qmd
    - qmd/6_random_sub.qmd
    - qmd/references.qmd
  navbar:
    search: true
  favicon: plots/img/grouse_silhouette.png

bibliography: bibliography.bib

format:
  html:
    theme: flatly
    toc: true
    mainfont: Georgia, serif
    code-fold: true

editor: visual
execute: 
  eval: false
