## generated by : /home/cactus/cactus_env/bin/cactus-update-prepare add branch --parentGenome birdAnc334 --childGenome Tympanuchus_cupido data/363-avian-reduced.hal data/input.txt --cactus-prepare-options '--alignCores 4' --topBranchLength 0.01 --outDir scratch/tmp/steps-output --jobStore scratch/tmp/js --ancestorName AncX
## date : 2023-10-06 19:18:22.026527
## cactus commit : 4823037fe5038c8d2a9dd29a159e153e74a1aab5
## wrapping : /home/cactus/cactus_env/bin/cactus-prepare scratch/tmp/steps-output/seq_file.in --outDir scratch/tmp/steps-output --outSeqFile scratch/tmp/steps-output/seq_file.out --jobStore scratch/tmp/js --alignCores 4 --outHal scratch/tmp/steps-output/birdAnc334.hal


## Preprocessor
cactus-preprocess scratch/tmp/js/0 scratch/tmp/steps-output/seq_file.in scratch/tmp/steps-output/seq_file.out --inputNames Lyrurus_tetrix --realTimeLogging --logInfo --retryCount 0 --maskMode none

## Alignment

### Round 0
cactus-blast scratch/tmp/js/1 scratch/tmp/steps-output/seq_file.out scratch/tmp/steps-output/AncX.cigar --root AncX --restart 
cactus-align scratch/tmp/js/2 scratch/tmp/steps-output/seq_file.out scratch/tmp/steps-output/AncX.cigar scratch/tmp/steps-output/AncX.hal --root AncX  --maxCores 8 
hal2fasta scratch/tmp/steps-output/AncX.hal AncX --hdf5InMemory > scratch/tmp/steps-output/AncX.fa 

### Round 1
cactus-blast scratch/tmp/js/3 scratch/tmp/steps-output/seq_file.out scratch/tmp/steps-output/birdAnc334.cigar --root birdAnc334 --includeRoot  
cactus-align scratch/tmp/js/4 scratch/tmp/steps-output/seq_file.out scratch/tmp/steps-output/birdAnc334.cigar scratch/tmp/steps-output/birdAnc334.hal --root birdAnc334  --maxCores 4 --includeRoot  

## Alignment update
halAddToBranch data/genomic/intermediate/cactus/363-avian-reduced.hal scratch/tmp/steps-output/AncX.hal scratch/tmp/steps-output/birdAnc334.hal birdAnc334 AncX Tympanuchus_cupido Lyrurus_tetrix 0.01 1.0 --hdf5InMemory 

## Alignment validation
halValidate --genome birdAnc334 data/genomic/intermediate/cactus/363-avian-reduced.hal --hdf5InMemory
halValidate --genome AncX data/genomic/intermediate/cactus/363-avian-reduced.hal --hdf5InMemory
halValidate --genome Tympanuchus_cupido data/genomic/intermediate/cactus/363-avian-reduced.hal --hdf5InMemory
halValidate --genome Lyrurus_tetrix data/genomic/intermediate/cactus/363-avian-reduced.hal --hdf5InMemory

